### ISSUE TITLE
New fakebook theme

### ISSUE THREAD

**Issue by lianglee** [happyhiveworker/ossnfacebook#11]
It seems the theme forked from sathish4fri its too old since that its been alot of changes to OSSN themes ,  maybe its better to use https://www.opensource-socialnetwork.org/component/view/2243/fake-book and improve it.  This theme should work fine on OSSN 5.6 with little changes required in profile menu.

**Comment by AntzCode** [comment]
> It seems the theme forked from sathish4fri its too old since that its been alot of changes to OSSN themes , maybe its better to use https://www.opensource-socialnetwork.org/component/view/2243/fake-book and improve it. This theme should work fine on OSSN 5.6 with little changes required in profile menu.

@lianglee Thanks for that. I have copied some changes from the latest file at that link but I also have found that it does have a few bugs and it breaks as soon as the theme is enabled. I'll show you some screenshots of it: 

## Facebook 3.6
![facebook-3 6](https://user-images.githubusercontent.com/64985097/128316762-8d86c9e1-5b35-4c15-b92f-312f127ec26a.png)
![Screenshot at 2021-08-05 20-17-06](https://user-images.githubusercontent.com/64985097/128316775-caf89eb4-cbb4-4057-8dab-fd34746e3003.png)

## Fakebook 5.6.0-rc.1
![fakebook-5 6 0-rc 1](https://user-images.githubusercontent.com/64985097/128316774-7c803128-e943-443c-a390-69c5206a3796.png)

There's not a big difference between the two projects though, and most of the differences are in the CSS.

**Comment by AntzCode** [comment]
> maybe its better to use https://www.opensource-socialnetwork.org/component/view/2243/fake-book and improve it.

@lianglee Could you tell me whether the code for that release is on github? Perhaps it would be better to branch my fork from that one if it is being actively developed.

**Comment by lianglee** [comment]
The GitHub branch is only fir future release.

You should download latest production release from our Website which
requires php 7.x and can't work on php8
