### ISSUE TITLE
White screen when enabling template

### ISSUE THREAD

**Issue by nico-m-dev** [happyhiveworker/ossnfacebook#7]
Hi, 
I install the theme in ossn version 5.6. 
Install goes well, but when i click enable i get this error: [https://www.wakkervlaanderen.org/error/error.jpg]https://www.wakkervlaanderen.org/error/error.jpg

Now both admin and site have a white screen.

**Comment by AntzCode** [comment]
Owed to breaking changes from core 5.2 > 5.6. This has been fixed in Fakebook v5.6.
